# Generated by Django 4.2.3 on 2023-07-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_alter_mytickets_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytickets',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
